name: Automatic Merge

on:
  schedule:
    - cron:  '1 * * * *'

jobs:
  merge:
    name: Merge Pull Requests
    runs-on: ubuntu-latest

    steps:
    - name: merge
      uses: nucleos/auto-merge-action@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
