name: Continuous Integration Tests

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  execute_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2

      - name: Install python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install project Dependencies
        run: poetry install

      - name: Execute Black Linter
        run: poetry run black src --check

  execute_import_sorter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2

      - name: Install python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install Project Dependencies
        run: poetry install

      - name: Execute Import Sorter
        run: poetry run isort src

  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2
         
      - name: Install python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install Project Dependencies
        run: poetry install

      - name: Execute Unit-tests
        run: poetry run python3 -m unittest tests/test_calculator.py

        
  auto_merge:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        merge-method: 'merge' # Default 'squash'
        min-approvals: 2 # Default 2
        base-ref: 'dev' # Default 'dev
