name: Continuous Integration Tests

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  execute_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2

      - name: Install python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install project Dependencies
        run: poetry install

      - name: Execute Black Linter
        run: poetry run black src --check

  execute_import_sorter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2

      - name: Install python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install Project Dependencies
        run: poetry install

      - name: Execute Import Sorter
        run: poetry run isort src

  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2
         
      - name: Install python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Install Project Dependencies
        run: poetry install

      - name: Execute Unit-tests
        run: poetry run python3 -m unittest tests/test_calculator.py

        
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          # The label name to automatically merge. Default is "automerge".
          label-name:
          # The number of reviewers to automatically merge. Default is 1.
          reviewers-number:
          # The merge method ("merge", "squash", "rebase"). Default is "merge"
          merge-method:
          # Let the bot delete the merged branch. true or false.
          auto-delete:
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.GITHUB_TOKEN }}
